<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- This is the most appropriate target framework for the game's Unity version. -->
    <TargetFramework>netstandard2.1</TargetFramework>
    <!-- This is the GUID of your mod. Example: com.github.YourAccount.BepInExTemplate -->
    <AssemblyName>legocool.LuckyBlocks</AssemblyName>
    <!-- This is the display name of your mod. Example: BepInEx Template -->
    <AssemblyTitle>Lucky_Blocks</AssemblyTitle>
    <!-- This is the version number of your mod. -->
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PEAKModding.PEAKLib.Core" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PEAKModding.PEAKLib.Items" Version="*" />
  </ItemGroup>

</Project>
